name: pytest

on: [push, pull_request]  # 触发测试的事件，可以根据需求进行调整

jobs:
  test:
    runs-on: ubuntu-latest  # 使用最新版的Ubuntu环境

    steps:
      - name: Checkout repository  # 检出代码仓库
        uses: actions/checkout@v2

      - name: Set up Python  # 配置Python环境
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # 使用所需的Python版本

      - name: Install Poetry  # 安装Poetry
        run: |
          curl -sSL https://install.python-poetry.org | python -
          export PATH="$HOME/.poetry/bin:$PATH"

      - name: Install dependencies  # 安装依赖项
        run: |
          poetry install --no-dev
          poetry add pytest --dev  # 安装pytest

      - name: Run tests  # 运行测试
        run: |
          poetry run pytest -v tests --log-cli-level=DEBUG > test_log.txt 2>&1  # 运行tests文件夹中的测试用例，并将日志输出到test_log.txt文件

      - name: Upload logs  # 上传日志到artifacts
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: test_log.txt  # 上传test_log.txt文件

